OPENSUSE Tumbleweed script done.

diff --git a/bootstrap b/bootstrap
--- a/bootstrap
+++ b/bootstrap
@@ -8,8 +8,13 @@ if $(grep -q '^Ubuntu 16.04' /etc/issue 2> /dev/null) ; then
     UPDATE_PY='_update_settings_on_this_machine.py'
 elif $(grep -q '^Ubuntu 18.04' /etc/issue 2> /dev/null) ; then
     UPDATE_PY='_update_settings_on_this_machine18.py'
+elif $(grep -q '^Welcome to openSUSE Tumbleweed' /etc/issue 2> /dev/null) ; then
+    UPDATE_PY='_update_settings_on_this_machine_suseT.py'
 else
-    >&2 echo 'Error: This is neither Ubuntu 16.04 nor 18.04'
+    >&2 echo 'Error: OS/Distribution not supported. Supported OS:'
+    >&2 echo '       Ubuntu 16.04'
+    >&2 echo '       Ubuntu 18.04'
+    >&2 echo '       openSUSE Tumbeweed'
     exit 1
 fi
 test "$( id -u )" = 0 || { >&2 echo 'Error: You are not root, please use "sudo" to run the script'; exit 1; }
