rename workstation_routines.py -> manage-this-machine

diff --git a/provision b/provision
--- a/provision
+++ b/provision
@@ -29,7 +29,7 @@ cd "$TEMP_DIR/cluster"
 # ----------------------------------------------------------------------------
 
 echo 'Trying to acquire a lock...'
-if ./workstation_routines.py lock
+if ./manage-this-machine lock
 then
     echo 'Trying to acquire a lock...  DONE'
 else
@@ -40,41 +40,41 @@ fi
 # ----------------------------------------------------------------------------
 
 echo 'Checking whether this host is already listed in fcl.json...'
-if ./workstation_routines.py check-this-host-in-json
+if ./manage-this-machine check-this-host-in-json
 then
     echo 'Checking whether this host is already listed in fcl.json...  DONE'
 else
-    >&2 echo 'Error: the command `./workstation_routines.py check-this-host-in-json` failed'
-    ./workstation_routines.py unlock
+    >&2 echo 'Error: the command `./manage-this-machine check-this-host-in-json` failed'
+    ./manage-this-machine unlock
     exit 1
 fi
 
 # ----------------------------------------------------------------------------
 
 echo 'Checking whether fcl.json is applicable for this host...'
-if ./workstation_routines.py check-json-applicability
+if ./manage-this-machine check-json-applicability
 then
     echo 'Checking whether fcl.json is applicable for this host...  DONE'
 else
-    >&2 echo 'Error: the command `./workstation_routines.py check-json-applicability` failed'
-    ./workstation_routines.py unlock
+    >&2 echo 'Error: the command `./manage-this-machine check-json-applicability` failed'
+    ./manage-this-machine unlock
     exit 1
 fi
 
 # ----------------------------------------------------------------------------
 
 echo 'Applying fcl.json to this host...'
-if ./workstation_routines.py apply-json
+if ./manage-this-machine apply-json
 then
     echo 'Applying fcl.json to this host...  DONE'
 else
-    >&2 echo 'Error: the command `./workstation_routines.py apply-json` failed'
-    ./workstation_routines.py unlock
+    >&2 echo 'Error: the command `./manage-this-machine apply-json` failed'
+    ./manage-this-machine unlock
     exit 1
 fi
 
 # ----------------------------------------------------------------------------
 
 echo 'Releasing the lock...'
-./workstation_routines.py unlock
+./manage-this-machine unlock
 echo 'Releasing the lock...  DONE'
